# Generated by Django 4.0.3 on 2022-12-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VenueList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('priority', models.TextField()),
                ('dateof', models.DateField(auto_now_add=True)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
